
###################  自定义项目配置 ###################
xncoding:
  socket-port: 9099    #socket端口
  ping-interval: 60000 #Ping消息间隔（毫秒）
  ping-timeout: 180000 #Ping消息超时时间（毫秒）

###################  spring配置  ###################
spring:
  profiles:
    active: dev

---
